[ADD][account_tax_cash_basis_fix_currency_rate] - Use of analytic acc…
Jarsa/account-fix-tools pull request #14
Opened 2017-08-07 16:13 UTC by ougc27

…ounts in the exchange difference.

2017-08-07 16:27 UTC, ougc27 commented
@alan196 Could you check this Pull Request?.

This PR has a improve adding the analytic account to the expense lines of the currency exchange difference journal entry.

2017-08-07 18:15 UTC, alan196 commented
Check gitignore file you are adding .pyc files

2017-08-07 18:20 UTC, alan196 requested changes

2017-08-07 18:20 UTC, alan196 commented on account_tax_cash_basis_fix_currency_rate_difference/models/account_partial_reconcile.py
> +            total_analytic_account = len(analytic_accounts)
you can use `if analytic_accounts:` 

You don't need to use len.

if you test an empty list you will get False.

2017-08-07 18:20 UTC, alan196 commented on account_tax_cash_basis_fix_currency_rate_difference/models/account_partial_reconcile.py
> +                analytic_accounts = False
why you need a False? If you return an empty list what happens?

2017-08-07 18:20 UTC, alan196 commented on account_tax_cash_basis_fix_currency_rate_difference/models/account_partial_reconcile.py
> +                analytic_accounts = list(set(analytic_accounts))[0]
What will happen if you get more than 1 analytic account? You will miss it.

2017-08-07 18:20 UTC, alan196 commented on account_tax_cash_basis_fix_currency_rate_difference/models/account_partial_reconcile.py
> +                        'analytic_account_id': analytic_accounts,
try to send the empty list, if it fails you can use:

`analytic_accounts if analytic_accounts else False`

2017-08-07 18:28 UTC, ougc27 commented on account_tax_cash_basis_fix_currency_rate_difference/models/account_partial_reconcile.py
> +                analytic_accounts = list(set(analytic_accounts))[0]
In this case, what is the better way to adapt this field to the journal entry?

2017-08-09 14:57 UTC, alan196 requested changes

2017-08-09 14:57 UTC, alan196 commented on account_tax_cash_basis_fix_currency_rate_difference/models/account_move.py
> +    nbr_diff_moves = fields.Float(
Why nbr? Please add help to explain this field.

2017-08-09 14:57 UTC, alan196 commented on account_tax_cash_basis_fix_currency_rate_difference/models/account_move.py
> +        'account.move',
Add string to name the field even if the field is not in the view

2017-08-09 14:57 UTC, alan196 commented on account_tax_cash_basis_fix_currency_rate_difference/models/account_partial_reconcile.py
> +                import ipdb; ipdb.set_trace()
Please delete the ipdb 👎

2017-10-02 21:43 UTC, closed without merging