[FIX][res_partner_statement]
Jarsa/account-fix-tools pull request #9
Opened 2017-07-26 17:40 UTC by SaraiOsorio

@alan196

2017-07-26 21:53 UTC, alan196 requested changes

2017-07-26 21:53 UTC, alan196 commented on res_partner_statement/wizard/partner_statement_wizard.py
> +                            if payment == line[0]:
too many nested blocks in travis.
You need to refactor an create another function.

2017-07-28 23:57 UTC, SaraiOsorio commented
@AlexisReza

2017-08-15 15:08 UTC, SaraiOsorio commented
@ougc27

2017-08-15 16:41 UTC, ougc27 approved these changes

2017-08-15 16:44 UTC, alan196 approved these changes

2017-08-15 23:24 UTC, merged